name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk

    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install python-tk

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow

    - name: Generate icons
      run: python generate_icons.py

    - name: Build executable
      run: python build_exe.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DuplicateFileDetector-${{ matrix.os }}
        path: |
          dist/DuplicateFileDetector*
          README.md
          LICENSE
          RELEASE.md
          screenshots/*

    - name: Upload to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/DuplicateFileDetector*
          README.md
          LICENSE
          RELEASE.md
          screenshots/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}